# General parameters
dataset: CaliforniaHousing
model_name: LinearModel # LinearModel, KNN, SVM, DecisionTree, RandomForest, MLP
                           # XGBoost, CatBoost, LightGBM,
                           # TabNet, VIME, TabTransformer, ModelTree, NODE, DeepGBM, RLN, DNFNet, STG, NAM, DeepFM
objective: regression

# GPU parameters
use_gpu: 'false'
gpu_id: 0

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: 'true'
seed: 221

# Preprocessing parameters
scale: 'true'
target_encode: 'false'

# Training parameters
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_features: 8
num_classes: 1 # always one for regression!