# General parameters
dataset: Adult
model_name: NAM # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG
objective: binary_classification # Don't change

# GPU parameters
use_gpu: 'false'
gpu_id: 0

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: maximize

# Cross validation parameters
num_splits: 3
shuffle: 'true'
seed: 221 # Don't change

# Preprocessing parameters
scale: 'true'
target_encode: 'true'
one_hot_encode: 'false'

# Training parameters
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 1  # for classification
num_features: 14
cat_idx: [1,3,5,6,7,8,9,13]