# General parameters
dataset: Covertype
model_name: MLP # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree, TabNet
objective: classification # Don't change

# Optuna parameters - https://optuna.org/
n_trials: 10
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: 'true'
seed: 221 # Don't change

# Preprocessing parameters
scale: 'true'
target_encode: 'true'
target_one_hot_encode: 'false'

# Training parameters
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 7 # for classification
num_features: 54