# General parameters
dataset: KddCup99
model_name: VIME # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, MLP, TabNet, VIME, TabTransformer
objective: classification # Don't change

# GPU parameters
use_gpu: 'false'
gpu_id: 0

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: minimize

# Cross validation parameters
num_splits: 3
shuffle: 'true'
seed: 221 # Don't change

# Preprocessing parameters
scale: 'false'
target_encode: 'true'

# Training parameters
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 4 # for classification
num_features: 41
cat_idx: [1,2,3]