# General parameters
dataset: Covertype
model_name: STG # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM,
    # ModelTree, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: classification # Don't change

# GPU parameters
use_gpu: 'false'
gpu_ids: [0, 1]
data_parallel: 'true'

# Optuna parameters - https://optuna.org/
n_trials: 1
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: 'true'
seed: 221 # Don't change

# Preprocessing parameters
scale: 'true'
target_encode: 'true'

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 7 # for classification
num_features: 54